
# Linear Algebra: Matrix Operations, Eigenvalues, Eigenvectors, and Decomposition Methods

## Overview
Linear algebra is a foundational aspect of mathematics, especially important in fields like data science, machine learning, physics, and finance. In this notebook, we'll explore core concepts including:

- Matrix operations (addition, multiplication, inversion)
- Eigenvalues and eigenvectors
- Matrix decompositions: LU and QR


## 1. Matrix Operations

Matrix operations are fundamental in linear algebra, allowing manipulation of matrices in various ways. We’ll cover:

1. Matrix addition and multiplication
2. Matrix inversion
3. Transpose of a matrix


In [1]:

import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C_add = A + B
print("Matrix Addition (A + B):\n", C_add)

# Matrix multiplication
C_mult = np.dot(A, B)
print("\nMatrix Multiplication (A * B):\n", C_mult)

# Matrix inversion
A_inv = np.linalg.inv(A)
print("\nMatrix Inversion (A^-1):\n", A_inv)

# Transpose of a matrix
A_transpose = A.T
print("\nTranspose of Matrix A (A^T):\n", A_transpose)


Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]

Matrix Multiplication (A * B):
 [[19 22]
 [43 50]]

Matrix Inversion (A^-1):
 [[-2.   1. ]
 [ 1.5 -0.5]]

Transpose of Matrix A (A^T):
 [[1 3]
 [2 4]]



## 2. Eigenvalues and Eigenvectors

Eigenvalues and eigenvectors play a key role in understanding the properties of matrices, such as in principal component analysis (PCA).

For a matrix \( A \), an eigenvector \( v \) and eigenvalue \( \lambda \) satisfy:

\[ A \cdot v = \lambda \cdot v \]

Let's calculate the eigenvalues and eigenvectors of matrix \( A \).


In [2]:

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:\n", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)


Eigenvalues of A:
 [-0.37228132  5.37228132]

Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



## 3. LU Decomposition

LU decomposition factors a matrix \( A \) into the product of a lower triangular matrix \( L \) and an upper triangular matrix \( U \). This decomposition is useful for solving systems of linear equations.

Let's perform an LU decomposition on matrix \( A \).


In [4]:
from scipy.linalg import lu

# LU decomposition
P, L, U = lu(A)
print("Lower Triangular Matrix L:\n", L)
print("\nUpper Triangular Matrix U:\n", U)
print("\nPermutation Matrix P:\n", P)


Lower Triangular Matrix L:
 [[1.         0.        ]
 [0.33333333 1.        ]]

Upper Triangular Matrix U:
 [[3.         4.        ]
 [0.         0.66666667]]

Permutation Matrix P:
 [[0. 1.]
 [1. 0.]]



## 4. QR Decomposition

QR decomposition factors a matrix \( A \) into an orthogonal matrix \( Q \) and an upper triangular matrix \( R \). This decomposition is commonly used in least squares fitting and numerical solutions.

Let's perform a QR decomposition on matrix \( A \).


In [ ]:
# QR decomposition
Q, R = np.linalg.qr(A)
print("Orthogonal Matrix Q:\n", Q)
print("\nUpper Triangular Matrix R:\n", R)


Orthogonal Matrix Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

Upper Triangular Matrix R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]



## Summary

In this notebook, we covered:

- Basic matrix operations: addition, multiplication, inversion, and transpose
- Eigenvalues and eigenvectors
- LU decomposition for solving systems of linear equations
- QR decomposition for applications in least squares fitting
